source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'erubis'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'sinatra'
gem 'unicorn'
gem 'hiredis'
group :development do
  gem 'foreman'
  gem 'sinatra-contrib', require: nil
  gem 'redis'
  gem 'stackprof'
  gem 'rblineprof'
  gem 'rack-lineprof'
end
